export default {
    LAUNCH_APP: 'LAUNCH_APP',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
}